services:
  chatbot-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8000/stream
    networks:
      - chatbot-network
    restart: unless-stopped

  chatbot-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  chatbot-network:
    name: chatbot-network
    driver: bridge